# The docker-compose file you deliver needs to:
# - Define which ports are exposed, and what they map to in your challenge
# - Name the container
# - Define the folder that your dockerfile (and challenge source code) exists in

# The version MUST be 3. If you test on a docker-compose that's not 3, it won't go nicely.
version: '3'

# This is general structure of the docker-compose file that will be used in prod
services:

# Name is <category>-<tier>
  exp-3:
  # Your container name is <category>-<tier>
    container_name: exp-3
    # This should be the directory your dockerfile exists in.
    # Note, other challenges will live in ./ too, so ensure your directory name is adequately unique (comapnyname-challengename)
    build: ./your-challenge/
    # Ports! the syntax is <external>:<containerlocal>
    # Ensure the external port is within the correct range. You can use whatever local port you wish (as long as it doesn't break anything)
    ports:
      - 4300:2222

  # From here onwards is demonstrating how other peoples challenges will be loaded adjacent to yours
  # We will only have one docker-compose file, concatenating all participants docker-compose files together to build the production document
  # Once you understand that, you should remove these so you're not constantly building/running random apps during the development of your own challenge
  web-3:
    container_name: web-3
    build: ./some-other-challenge-2/
    ports:
      - 1300:80

  crypto-2:
    container_name: crypto-2
    build: ./some-other-challenge/
    ports:
      - 3200:10000
